# Name and desciption sof your task
task_name: "linktree-task"
task_description: "linktree-task"
# network value can be DEVELOPMENT , ARWEAVE or IPFS
task_executable_network: "DEVELOPMENT"
# Provide your web.storage key in case of IPFS otherwise leave blank
secret_web3_storage_key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweGY0ODYxMzAzOTdDNTY1QzlDYTRCOTUzZTA2RWQ4NUI4MGRBQzRkYTIiLCJpc3MiOiJ3ZWIzLXN0b3JhZ2UiLCJpYXQiOjE2NjYzNjU1OTk5MDMsIm5hbWUiOiJTb21hIn0.TU-KUFS9vjI9blN5dx6VsLLuIjJnpjPrxDHBvjXQUxw"

# Path to your executable webpack if the selected network is IPFS otherwise leave blank
task_audit_program: "/home/soma/code-ie/task-template-linktree/dist/main.js"

# Provide your transaction ID in case of ARWEAVE and in case of DEVELOPMENT give your executable name as main otherwise leave blank
task_audit_program_id: "main"

# Total round time of your task : it must be given in slots and each slot is rougly equal to 4ms
round_time: "600"

audit_window: "200"
submission_window: "200"

# Amounts in KOII

minimum_stake_amount: "5"
total_bounty_amount: "10"
bounty_amount_per_round: "1"

#Number of times allowed to re-submit the distribution  list in case the distribution list is audited
allowed_failed_distributions: "4"

# CID of metadata
task_metadata: ""
task_locals: ""
koii_vars: ""

#Space in MBs
space: "10"
